### ISSUE TITLE
Category filters showing error message

### ISSUE THREAD

**Issue by Bongasman** [utklasad/magento2-admin-product-grid-category-filter#6]
Hi, 
I installed you extension and its nice  but it does not filter shows error red band, this is console error: http://prntscr.com/ld927q

**Comment by utklasad** [comment]
Hi @Bongasman 

I've not encounterd this error before. What Magento2 version are you using?

Do you have any other modules installed that's modifying the admin product grid?

If you provide me some more information I will take a look at this asap.

**Comment by Bongasman** [comment]
Hi, 
I have other extension that might possibly be modifying product grid like the Amasty bulk product update extension, I am using Mag 2.2.2

**Comment by utklasad** [comment]
Hi @Bongasman 

I can't reproduce this issue and I'm not able to test "Amasty bulk product update extension". Feel free to fork the repo and do a PR if you find any solution to fix the issue regarding this module and the "Amasty bulk".
