### ISSUE TITLE
Related, upsell and Cross-sell Products cannot be added

### ISSUE THREAD

**Issue by Quedendil** [utklasad/magento2-admin-product-grid-category-filter#9]
Hi! I installed your extension and it's really useful, but I have encountered a problem with related, upsell and Cross-sell Products.
When I am trying to add a related/upsell/Cross-sell product I am getting the following error:

An error has happened during application run. See exception log for details. 

Error: Class 'Utklasad\AdminProductGridCategoryFilter\Ui\DataProvider\Product\Related\AbstractDataProvider' not found

Magento Version 2.4.1

**Comment by cavalier79** [comment]
There's an error in the files.

class UpSellDataProvider extends AbstractDataProvider

Must be fixed in 

class UpSellDataProvider extends \Magento\Catalog\Ui\DataProvider\Product\Related\AbstractDataProvider


also for related

**Comment by utklasad** [comment]
Thanks for the report and PR @cavalier79 . This issue will be fixed in next release.
